examples: dhcp_client: fix compile error
When building dhcp_client, it appears that including linux/if_arp.h
requires sys/socket.h for the sockaddr definition (at least on my
system). I fixed the same issue with ell/net.c but never build
dhcp_client. Below is one of the errors I saw when building:

In file included from /usr/include/linux/netdevice.h:28,
                 from /usr/include/linux/if_arp.h:26,
                 from examples/dhcp-client.c:31:
/usr/include/linux/if.h:234:19: error: field ‘ifru_addr’ has incomplete type
   struct sockaddr ifru_addr;