dbus: Fix unused variable warning
ell/dbus-util.c: In function '_dbus1_builder_finish':
ell/dbus-util.c:964:20: error: variable 'root' set but not used
[-Werror=unused-but-set-variable]