dbus: Fix compiler warning on 32-bit
ell/dbus-kernel.c:388:22: error: cast from pointer to integer of
different size [-Werror=pointer-to-int-cast]

ell/dbus-kernel.c:396:23: error: cast from pointer to integer of
different size [-Werror=pointer-to-int-cast]

Casting void* to uint64_t on 32-bit x86 causes a build error with gcc
5.3.1, so cast to uintptr_t instead.