dbus: Fix unused variable warning
ell/dbus-util.c: In function '_dbus1_builder_append_basic':
ell/dbus-util.c:794:9: error: unused variable 'offset'
[-Werror=unused-variable]