dbus: Fix compile error for 32-bit platforms
Error encountered with 32-bit gcc 5.3.1:

ell/dbus-kernel.c:412:20: error: cast from pointer to integer of
different size [-Werror=pointer-to-int-cast]

Casting the pointer to uintptr_t instead of uint64_t works on both
32-bit and 64-bit platforms.