fswatch: add missing limits.h include for NAME_MAX
fixes compilation on stricter libcs like Musl.

ell/fswatch.c: In function 'inotify_read_cb':
ell/fswatch.c:80:45: error: 'NAME_MAX' undeclared (first use in this function); did you mean 'SIZE_MAX'?
  uint8_t buf[sizeof(struct inotify_event) + NAME_MAX + 1]
                                             ^~~~~~~~
                                             SIZE_MAX