build: add missing l_genl_family_set_unicast_handler
Add l_genl_family_set_unicast_handler (and remove legacy
l_genl_set_unicast_handler).

Fixes iwd compile failure:

  src/netdev.o: In function `netdev_set_nl80211':
  netdev.c:(.text+0x6f04): undefined reference to `l_genl_family_set_unicast_handler'